/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/NewRecord/": {
    get: operations["listNew_Records"];
    post: operations["createNew_Record"];
  };
  "/NewRecord/{id}/": {
    get: operations["retrieveNew_Record"];
    put: operations["updateNew_Record"];
    delete: operations["destroyNew_Record"];
    patch: operations["partialUpdateNew_Record"];
  };
}

export interface components {
  schemas: {
    NewRecords: {
      name: string;
      time?: string | null;
    };
  };
}

export interface operations {
  listNew_Records: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewRecords"][];
        };
      };
    };
  };
  createNew_Record: {
    parameters: {};
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["NewRecords"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewRecords"];
        "application/x-www-form-urlencoded": components["schemas"]["NewRecords"];
        "multipart/form-data": components["schemas"]["NewRecords"];
      };
    };
  };
  retrieveNew_Record: {
    parameters: {
      path: {
        /** A unique integer value identifying this new_ record. */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewRecords"];
        };
      };
    };
  };
  updateNew_Record: {
    parameters: {
      path: {
        /** A unique integer value identifying this new_ record. */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewRecords"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewRecords"];
        "application/x-www-form-urlencoded": components["schemas"]["NewRecords"];
        "multipart/form-data": components["schemas"]["NewRecords"];
      };
    };
  };
  destroyNew_Record: {
    parameters: {
      path: {
        /** A unique integer value identifying this new_ record. */
        id: string;
      };
    };
    responses: {
      204: never;
    };
  };
  partialUpdateNew_Record: {
    parameters: {
      path: {
        /** A unique integer value identifying this new_ record. */
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["NewRecords"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewRecords"];
        "application/x-www-form-urlencoded": components["schemas"]["NewRecords"];
        "multipart/form-data": components["schemas"]["NewRecords"];
      };
    };
  };
}

export interface external {}
